version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=5050
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5050
    depends_on:
      - backend

